# Generated by Django 5.0.1 on 2024-01-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_rename_proveedor_producto_proveedores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='categoria_unidad',
        ),
        migrations.DeleteModel(
            name='CategoriaUnidad',
        ),
    ]
