# Generated by Django 5.0.1 on 2024-02-01 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_remove_unidad_categoria_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gasto_mensual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ultimo_mes_gasto',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
